80 landing hero
hlxsites/Vonage pull request #115
Opened 2023-06-30 14:03 UTC by rrusher

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #80 

Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/
- After: https://80-landing-hero--vonage--hlxsites.hlx.page/unified-communications/

2023-06-30 18:24 UTC, synox commented
@rrusher the 2 buttons on https://80-landing-hero--vonage--hlxsites.hlx.page/unified-communications/business-phones/polycom-vvx-150 don't look right yet. 
<img width="554" alt="Screenshot 2023-06-30 at 11 23 56" src="https://github.com/hlxsites/Vonage/assets/2250964/dc641094-31a3-4e36-aa1f-c331ce9d344f">

2023-06-30 18:24 UTC, synox requested changes
see comment above

2023-06-30 19:28 UTC, rrusher commented
@synox Missed all the product pages. I'll get them now.

2023-07-01 01:57 UTC, dkuntze approved these changes

2023-07-01 01:58 UTC, merged